### ISSUE TITLE
Update to ProDOS 2.4.2

### ISSUE THREAD

**Issue by wyatt-wong** [a2stuff/prodos-drivers#10]
Would it be possible to update to ProDOS 2.4.2 as well ?

**Comment by inexorabletash** [comment]
I'm not sure what you mean. These work with any version of ProDOS 8 you want.

**Comment by wyatt-wong** [comment]
> I'm not sure what you mean. These work with any version of ProDOS 8 you want.

The release file prodos-drivers.po is not updated to ProDOS 2.4.2

**Comment by inexorabletash** [comment]
It doesn't include *any* version of `PRODOS`. It is not intended as a boot disk.

**Comment by wyatt-wong** [comment]
> It doesn't include _any_ version of `PRODOS`. It is not intended as a boot disk.

OK. I see that.
