### ISSUE TITLE
Crash of Sysutil when romx driver loaded

### ISSUE THREAD

**Issue by tsupplis** [a2stuff/prodos-drivers#12]
I noted a side effect of romx driver being loaded.
Sysutil crash on exit if sysutil loaded one of the modules.
To reproduce
- load romx driver after prodos
- Exercice sysutil (for example catalog a disk)
- Quit
This should result in a crash and switching to the monitor

It happens on a 2e with prodos 2.0.3 or 2.4.2.

I am at loss on debugging. I suspect there is some overwrite of the driver when util.x is loaded by sysutil.system

**Comment by tsupplis** [comment]
Close by Jeff's fix

**Comment by inexorabletash** [comment]
Oh, wow, I didn't even see this bug report. Glad it's sorted out!
